"""
Basic haiku context-template golden-path scenario.

Runs a real context-template + chat-agent end-to-end flow:
- context manager generates seed words into context
- chat agent receives those words plus chat instructions
- final response is validated against generated seed words
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from validation.core.base_scenario import BaseScenario


class BasicHaikuContextTemplateScenario(BaseScenario):
    """Golden-path context-template + chat-agent execution with live model responses."""

    async def test_scenario(self):
        vault = self.create_vault("HaikuContextVault")

        self.copy_files("validation/templates/files/test_image.jpg", vault, "images")
        self.create_file(
            vault,
            "AssistantMD/ContextTemplates/basic_haiku_context.md",
            BASIC_HAIKU_CONTEXT_TEMPLATE,
        )
        self.create_file(
            vault,
            "AssistantMD/ContextTemplates/basic_haiku_context_monty.md",
            BASIC_HAIKU_CONTEXT_TEMPLATE_MONTY,
        )
        self.create_file(
            vault,
            "notes/haiku_context_seed.md",
            HAIKU_CONTEXT_SEED_NOTE,
        )

        await self.start_system()

        first_payload = {
            "vault_name": vault.name,
            "prompt": "Write a haiku that uses all seed words from context exactly as provided.",
            "tools": [],
            "model": "gpt-mini",
            "context_template": "basic_haiku_context.md",
        }

        checkpoint = self.event_checkpoint()
        first_response = self.call_api("/api/chat/execute", method="POST", data=first_payload)
        assert first_response.status_code == 200, "Initial context chat should succeed"
        first_json = first_response.json()
        session_id = first_json.get("session_id")
        assert session_id, "Context chat should return a session id"

        events = self.events_since(checkpoint)
        self.assert_event_contains(
            events,
            name="context_template_loaded",
            expected={
                "template_name": "basic_haiku_context.md",
                "template_source": "vault",
            },
        )
        self.assert_event_contains(
            events,
            name="context_input_files_resolved",
            expected={
                "section_name": "Seed Words",
                "file_count": 1,
            },
        )
        self.assert_event_contains(
            events,
            name="context_section_completed",
            expected={"section_name": "Seed Words", "from_cache": False},
        )
        self.assert_event_contains(
            events,
            name="context_summary_persisted",
            expected={"sections": ["Seed Words"]},
        )
        self.assert_event_contains(
            events,
            name="context_history_compiled",
            expected={"latest_user_included": True},
        )

        seeds_path = vault / "outputs" / "haiku-seed-words.md"
        assert seeds_path.exists(), "Expected seed words file generated by context manager"

        second_payload = {
            "vault_name": vault.name,
            "prompt": "Write a haiku that uses all seed words from context exactly as provided.",
            "tools": [],
            "model": "gpt-mini",
            "context_template": "basic_haiku_context_monty.md",
        }

        checkpoint = self.event_checkpoint()
        second_response = self.call_api("/api/chat/execute", method="POST", data=second_payload)
        assert second_response.status_code == 200, "Monty context chat should succeed"
        second_json = second_response.json()
        second_session_id = second_json.get("session_id")
        assert second_session_id, "Monty context chat should return a session id"

        events = self.events_since(checkpoint)
        self.assert_event_contains(
            events,
            name="context_template_loaded",
            expected={
                "template_name": "basic_haiku_context_monty.md",
                "template_source": "vault",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_monty_execution_started",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_call_tool_started",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
                "tool": "file_ops_safe",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_call_tool_completed",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
                "tool": "file_ops_safe",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_generate_started",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_generate_completed",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_call_tool_completed",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
                "tool": "file_ops_safe",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_assemble_context_completed",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="context_section_completed",
            expected={
                "section_name": "Build haiku seed words into downstream chat context and persist the seed artifact.",
                "from_cache": False,
            },
        )
        self.assert_event_contains(
            events,
            name="context_summary_persisted",
            expected={
                "sections": [
                    "Build haiku seed words into downstream chat context and persist the seed artifact."
                ]
            },
        )
        self.assert_event_contains(
            events,
            name="context_history_compiled",
            expected={"latest_user_included": True},
        )

        monty_seeds_path = vault / "outputs" / "haiku-seed-words-monty.md"
        assert monty_seeds_path.exists(), "Expected seed words file generated by Monty context template"

        await self.stop_system()
        self.teardown_scenario()


BASIC_HAIKU_CONTEXT_TEMPLATE = """---
passthrough_runs: 1
description: Basic haiku context-template happy path
---

## Chat Instructions
You are a concise poet.
When asked for a haiku, write exactly three lines and do not add commentary.

## Seed Words
@recent-runs 1
@recent-summaries 0
@input file: images/test_image.jpg
@output context
@output file: outputs/haiku-seed-words
@header Seed Words
@model gpt-mini

Choose exactly three vivid seed words inspired by the inputs.
Output exactly one line in this format:
SEED_WORDS: word1, word2, word3

"""


BASIC_HAIKU_CONTEXT_TEMPLATE_MONTY = """---
workflow_engine: monty
description: Basic haiku context-template happy path (Monty)
---
```python
\"\"\"Build haiku seed words into downstream chat context and persist the seed artifact.\"\"\"

import json

source = await call_tool(
    name="file_ops_safe",
    arguments={"operation": "read", "target": "notes/haiku_context_seed.md"},
)
source_text = source.output.split("\\n\\n", 1)[1] if "\\n\\n" in source.output else source.output
seed_words = await generate(
    prompt=(
        "Choose exactly three vivid seed words inspired by this note.\\n\\n"
        + source_text
    ),
    instructions=(
        "Output exactly one line in this format:\\n"
        "SEED_WORDS: word1, word2, word3"
    ),
    model="gpt-mini",
)

existing = await call_tool(
    name="file_ops_safe",
    arguments={"operation": "read", "target": "outputs/haiku-seed-words-monty.md"},
)
if existing.metadata.get("status") == "completed":
    await call_tool(
        name="file_ops_unsafe",
        arguments={
            "operation": "truncate",
            "path": "outputs/haiku-seed-words-monty.md",
            "confirm_path": "outputs/haiku-seed-words-monty.md",
        },
    )
    await call_tool(
        name="file_ops_safe",
        arguments={
            "operation": "append",
            "target": "outputs/haiku-seed-words-monty.md",
            "content": seed_words.output,
        },
    )
else:
    await call_tool(
        name="file_ops_safe",
        arguments={
            "operation": "write",
            "target": "outputs/haiku-seed-words-monty.md",
            "content": seed_words.output,
        },
    )

assembled = await assemble_context(
    instructions="You are a concise poet. When asked for a haiku, write exactly three lines and do not add commentary.",
    history=[
        {"role": item["role"], "content": item["content"]}
        for item in json.loads(
            (await call_tool(
                name="memory_ops",
                arguments={"operation": "get_history", "scope": "session", "limit": "all"},
            )).output
        )["items"]
    ],
    context_messages=[{"role": "system", "content": seed_words.output}],
)

assembled
```
"""


HAIKU_CONTEXT_SEED_NOTE = """Morning frost settles over the fence.
The garden is quiet except for a single bird call.
Sunlight is just starting to reach the grass.
"""
