"""
Basic haiku context-template golden-path scenario.

Runs a real context-template + chat-agent end-to-end flow:
- context manager generates seed words into context
- chat agent receives those words plus chat instructions
- final response is validated against generated seed words
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from validation.core.base_scenario import BaseScenario


class BasicHaikuContextTemplateScenario(BaseScenario):
    """Golden-path context-template + chat-agent execution with live model responses."""

    async def test_scenario(self):
        vault = self.create_vault("HaikuContextVault")

        self.copy_files("validation/templates/files/test_image.jpg", vault, "images")
        self.create_file(
            vault,
            "AssistantMD/Authoring/basic_haiku_context.md",
            BASIC_HAIKU_CONTEXT_TEMPLATE,
        )
        self.create_file(
            vault,
            "notes/haiku_context_seed.md",
            HAIKU_CONTEXT_SEED_NOTE,
        )

        await self.start_system()

        payload = {
            "vault_name": vault.name,
            "prompt": "Write a haiku that uses all seed words from context exactly as provided.",
            "tools": [],
            "model": "gpt-mini",
            "context_template": "basic_haiku_context.md",
        }

        checkpoint = self.event_checkpoint()
        response = self.call_api("/api/chat/execute", method="POST", data=payload)
        assert response.status_code == 200, "Context chat should succeed"
        session_id = response.json().get("session_id")
        assert session_id, "Context chat should return a session id"

        events = self.events_since(checkpoint)
        self.assert_event_contains(
            events,
            name="context_template_loaded",
            expected={
                "template_name": "basic_haiku_context.md",
                "template_source": "vault",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_monty_execution_started",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context.md/{session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_direct_tool_started",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context.md/{session_id}",
                "tool": "file_ops_safe",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_direct_tool_completed",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context.md/{session_id}",
                "tool": "file_ops_safe",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_generate_started",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context.md/{session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_generate_completed",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context.md/{session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_assemble_context_completed",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context.md/{session_id}",
                "message_count": 3,
            },
        )
        self.assert_event_contains(
            events,
            name="context_section_completed",
            expected={
                "section_name": "Build haiku seed words into downstream chat context and persist the seed artifact.",
                "from_cache": False,
            },
        )
        self.assert_event_contains(
            events,
            name="context_summary_persisted",
            expected={
                "sections": [
                    "Build haiku seed words into downstream chat context and persist the seed artifact."
                ]
            },
        )
        self.assert_event_contains(
            events,
            name="context_history_compiled",
            expected={"active_prompt_source": "history_processor_input"},
        )

        seeds_path = vault / "outputs" / "haiku-seed-words.md"
        assert seeds_path.exists(), "Expected seed words file generated by context template"

        await self.stop_system()
        self.teardown_scenario()


# === CONTEXT TEMPLATE ===

BASIC_HAIKU_CONTEXT_TEMPLATE = """---
run_type: context
description: Basic haiku context-template happy path
---
```python
\"\"\"Build haiku seed words into downstream chat context and persist the seed artifact.\"\"\"

source = await file_ops_safe(operation="read", path="notes/haiku_context_seed.md")
source_text = source.output.split("\\n\\n", 1)[1] if "\\n\\n" in source.output else source.output
seed_words = await generate(
    prompt=(
        "Choose exactly three vivid seed words inspired by this note.\\n\\n"
        + source_text
    ),
    instructions=(
        "Output exactly one line in this format:\\n"
        "SEED_WORDS: word1, word2, word3"
    ),
    model="gpt-mini",
)

existing = await file_ops_safe(operation="read", path="outputs/haiku-seed-words.md")
if existing.metadata.get("status") == "completed":
    await file_ops_unsafe(
        operation="truncate",
        path="outputs/haiku-seed-words.md",
        confirm_path="outputs/haiku-seed-words.md",
    )
    await file_ops_safe(
        operation="append",
        path="outputs/haiku-seed-words.md",
        content=seed_words.output,
    )
else:
    await file_ops_safe(
        operation="write",
        path="outputs/haiku-seed-words.md",
        content=seed_words.output,
    )

history = await retrieve_history(scope="session", limit="all")
assembled = await assemble_context(
    instructions="You are a concise poet. When asked for a haiku, write exactly three lines and do not add commentary.",
    history=history.items,
    context_messages=[
        {"role": "system", "content": seed_words.output},
        {
            "role": "system",
            "content": (
                "Latest message visible to context script: "
                + latest_message.role
                + " | "
                + latest_message.content
            ),
        },
    ],
)

assembled
```
"""


HAIKU_CONTEXT_SEED_NOTE = """Morning frost settles over the fence.
The garden is quiet except for a single bird call.
Sunlight is just starting to reach the grass.
"""
