"""
Basic haiku context-template golden-path scenario.

Runs a real context-template + chat-agent end-to-end flow:
- context manager generates seed words into context
- chat agent receives those words plus chat instructions
- final response is validated against generated seed words
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from validation.core.base_scenario import BaseScenario


class BasicHaikuContextTemplateScenario(BaseScenario):
    """Golden-path context-template + chat-agent execution with live model responses."""

    async def test_scenario(self):
        vault = self.create_vault("HaikuContextVault")

        self.copy_files("validation/templates/files/test_image.jpg", vault, "images")
        self.create_file(
            vault,
            "AssistantMD/ContextTemplates/basic_haiku_context.md",
            BASIC_HAIKU_CONTEXT_TEMPLATE,
        )

        await self.start_system()

        first_payload = {
            "vault_name": vault.name,
            "prompt": "Write a haiku that uses all seed words from context exactly as provided.",
            "tools": [],
            "model": "gpt-mini",
            "context_template": "basic_haiku_context.md",
        }

        checkpoint = self.event_checkpoint()
        first_response = self.call_api("/api/chat/execute", method="POST", data=first_payload)
        assert first_response.status_code == 200, "Initial context chat should succeed"
        first_json = first_response.json()
        session_id = first_json.get("session_id")
        assert session_id, "Context chat should return a session id"
        response_text = first_json.get("response", "")
        assert len(response_text.strip()) > 30, "Expected non-trivial live model response"

        events = self.events_since(checkpoint)
        self.assert_event_contains(
            events,
            name="context_template_loaded",
            expected={
                "template_name": "basic_haiku_context.md",
                "template_source": "vault",
            },
        )
        self.assert_event_contains(
            events,
            name="context_input_files_resolved",
            expected={
                "section_name": "Seed Words",
                "file_count": 1,
            },
        )
        self.assert_event_contains(
            events,
            name="context_section_completed",
            expected={"section_name": "Seed Words", "from_cache": False},
        )
        self.assert_event_contains(
            events,
            name="context_summary_persisted",
            expected={"sections": ["Seed Words"]},
        )
        self.assert_event_contains(
            events,
            name="context_history_compiled",
            expected={"latest_user_included": True},
        )

        seeds_path = vault / "outputs" / "haiku-seed-words.md"
        assert seeds_path.exists(), "Expected seed words file generated by context manager"
        assert response_text.strip(), "Expected non-empty chat response"

        await self.stop_system()
        self.teardown_scenario()


BASIC_HAIKU_CONTEXT_TEMPLATE = """---
passthrough_runs: 1
description: Basic haiku context-template happy path
---

## Chat Instructions
You are a concise poet.
When asked for a haiku, write exactly three lines and do not add commentary.

## Seed Words
@recent-runs 1
@recent-summaries 0
@input file: images/test_image.jpg
@output context
@output file: outputs/haiku-seed-words
@header Seed Words
@model gpt-mini

Choose exactly three vivid seed words inspired by the inputs.
Output exactly one line in this format:
SEED_WORDS: word1, word2, word3

"""
