"""
Basic haiku context-template golden-path scenario.

Runs a real context-template + chat-agent end-to-end flow:
- context manager generates seed words into context
- chat agent receives those words plus chat instructions
- final response is validated against generated seed words
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from validation.core.base_scenario import BaseScenario


class BasicHaikuContextTemplateScenario(BaseScenario):
    """Golden-path context-template + chat-agent execution with live model responses."""

    async def test_scenario(self):
        vault = self.create_vault("HaikuContextVault")

        self.copy_files("validation/templates/files/test_image.jpg", vault, "images")
        self.create_file(
            vault,
            "AssistantMD/ContextTemplates/basic_haiku_context.md",
            BASIC_HAIKU_CONTEXT_TEMPLATE,
        )
        self.create_file(
            vault,
            "AssistantMD/ContextTemplates/basic_haiku_context_monty.md",
            BASIC_HAIKU_CONTEXT_TEMPLATE_MONTY,
        )
        self.create_file(
            vault,
            "notes/haiku_context_seed.md",
            HAIKU_CONTEXT_SEED_NOTE,
        )

        await self.start_system()

        first_payload = {
            "vault_name": vault.name,
            "prompt": "Write a haiku that uses all seed words from context exactly as provided.",
            "tools": [],
            "model": "gpt-mini",
            "context_template": "basic_haiku_context.md",
        }

        checkpoint = self.event_checkpoint()
        first_response = self.call_api("/api/chat/execute", method="POST", data=first_payload)
        assert first_response.status_code == 200, "Initial context chat should succeed"
        first_json = first_response.json()
        session_id = first_json.get("session_id")
        assert session_id, "Context chat should return a session id"
        response_text = first_json.get("response", "")
        assert len(response_text.strip()) > 30, "Expected non-trivial live model response"

        events = self.events_since(checkpoint)
        self.assert_event_contains(
            events,
            name="context_template_loaded",
            expected={
                "template_name": "basic_haiku_context.md",
                "template_source": "vault",
            },
        )
        self.assert_event_contains(
            events,
            name="context_input_files_resolved",
            expected={
                "section_name": "Seed Words",
                "file_count": 1,
            },
        )
        self.assert_event_contains(
            events,
            name="context_section_completed",
            expected={"section_name": "Seed Words", "from_cache": False},
        )
        self.assert_event_contains(
            events,
            name="context_summary_persisted",
            expected={"sections": ["Seed Words"]},
        )
        self.assert_event_contains(
            events,
            name="context_history_compiled",
            expected={"latest_user_included": True},
        )

        seeds_path = vault / "outputs" / "haiku-seed-words.md"
        assert seeds_path.exists(), "Expected seed words file generated by context manager"
        assert response_text.strip(), "Expected non-empty chat response"

        second_payload = {
            "vault_name": vault.name,
            "prompt": "Write a haiku that uses all seed words from context exactly as provided.",
            "tools": [],
            "model": "gpt-mini",
            "context_template": "basic_haiku_context_monty.md",
        }

        checkpoint = self.event_checkpoint()
        second_response = self.call_api("/api/chat/execute", method="POST", data=second_payload)
        assert second_response.status_code == 200, "Monty context chat should succeed"
        second_json = second_response.json()
        second_session_id = second_json.get("session_id")
        assert second_session_id, "Monty context chat should return a session id"
        second_response_text = second_json.get("response", "")
        assert len(second_response_text.strip()) > 30, "Expected non-trivial live model response from Monty context"

        events = self.events_since(checkpoint)
        self.assert_event_contains(
            events,
            name="context_template_loaded",
            expected={
                "template_name": "basic_haiku_context_monty.md",
                "template_source": "vault",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_monty_execution_started",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_retrieve_allowed",
            expected={
                "type": "file",
                "ref": "notes/haiku_context_seed.md",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_retrieve_resolved",
            expected={
                "type": "file",
                "ref": "notes/haiku_context_seed.md",
                "item_count": 1,
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_generate_started",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_generate_completed",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_output_written",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
                "type": "file",
                "ref": "outputs/haiku-seed-words-monty.md",
            },
        )
        self.assert_event_contains(
            events,
            name="authoring_assemble_context_completed",
            expected={
                "workflow_id": f"{vault.name}/context/basic_haiku_context_monty.md/{second_session_id}",
            },
        )
        self.assert_event_contains(
            events,
            name="context_section_completed",
            expected={
                "section_name": "Build haiku seed words into downstream chat context and persist the seed artifact.",
                "from_cache": False,
            },
        )
        self.assert_event_contains(
            events,
            name="context_summary_persisted",
            expected={
                "sections": [
                    "Build haiku seed words into downstream chat context and persist the seed artifact."
                ]
            },
        )
        self.assert_event_contains(
            events,
            name="context_history_compiled",
            expected={"latest_user_included": True},
        )

        monty_seeds_path = vault / "outputs" / "haiku-seed-words-monty.md"
        assert monty_seeds_path.exists(), "Expected seed words file generated by Monty context template"
        assert second_response_text.strip(), "Expected non-empty Monty chat response"

        await self.stop_system()
        self.teardown_scenario()


BASIC_HAIKU_CONTEXT_TEMPLATE = """---
passthrough_runs: 1
description: Basic haiku context-template happy path
---

## Chat Instructions
You are a concise poet.
When asked for a haiku, write exactly three lines and do not add commentary.

## Seed Words
@recent-runs 1
@recent-summaries 0
@input file: images/test_image.jpg
@output context
@output file: outputs/haiku-seed-words
@header Seed Words
@model gpt-mini

Choose exactly three vivid seed words inspired by the inputs.
Output exactly one line in this format:
SEED_WORDS: word1, word2, word3

"""


BASIC_HAIKU_CONTEXT_TEMPLATE_MONTY = """---
workflow_engine: monty
description: Basic haiku context-template happy path (Monty)
authoring.capabilities: [retrieve, generate, output, assemble_context]
authoring.retrieve.file: [notes/haiku_context_seed.md]
authoring.output.file: [outputs/*.md]
---
```python
\"\"\"Build haiku seed words into downstream chat context and persist the seed artifact.\"\"\"

source = await retrieve(type="file", ref="notes/haiku_context_seed.md")
seed_words = await generate(
    prompt=(
        "Choose exactly three vivid seed words inspired by this note.\\n\\n"
        + source.items[0].content
    ),
    instructions=(
        "Output exactly one line in this format:\\n"
        "SEED_WORDS: word1, word2, word3"
    ),
    model="gpt-mini",
)

await output(
    type="file",
    ref="outputs/haiku-seed-words-monty.md",
    data=seed_words.output,
    options={"mode": "replace"},
)

assembled = await assemble_context(
    instructions=[
        "You are a concise poet. When asked for a haiku, write exactly three lines and do not add commentary."
    ],
    context_messages=[{"role": "system", "content": seed_words.output}],
    latest_user_message=latest_user_message,
)

assembled
```
"""


HAIKU_CONTEXT_SEED_NOTE = """Morning frost settles over the fence.
The garden is quiet except for a single bird call.
Sunlight is just starting to reach the grass.
"""
