"""Integration scenario for lightweight goal_ops persistence and tool behavior."""

from __future__ import annotations

import json
import sqlite3
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path
from types import SimpleNamespace

sys.path.insert(0, str(Path(__file__).resolve().parents[4]))

from core.authoring.shared.tool_binding import resolve_tool_binding
from core.goals import GoalOpsStore
from core.runtime.execution_tasks import (
    ExecutionTaskKind,
    ExecutionTaskSource,
    goal_task_metadata,
    workflow_vault_scope,
)
from core.runtime.state import get_runtime_context
from core.system_migrations import get_system_migration_status
from core.vault_state.file_mutations import mutate_vault_file
from validation.core.base_scenario import BaseScenario


class GoalOpsScenario(BaseScenario):
    """Validate durable goal_ops operations and lightweight plan semantics."""

    async def test_scenario(self):
        vault = self.create_vault("GoalOpsVault")
        await self.start_system()

        binding = resolve_tool_binding(["goal_ops"], vault_path=str(vault))
        self.soft_assert_equal(binding.tool_names(), ["goal_ops"], "goal_ops should bind through the tool registry")
        tool = binding.tool_specs[0].tool_function
        ctx = SimpleNamespace(deps=SimpleNamespace(vault_name=vault.name, session_id="goal_ops_chat_session"))

        initial_plan = [
            {"text": "Review source notes", "status": "pending"},
            {"text": "Draft briefing", "status": "pending"},
            {"text": "List open questions", "status": "pending"},
        ]
        goal_ops_activity_checkpoint = self.event_checkpoint()
        create_payload = await tool.function(
            ctx,
            operation="create_goal",
            data={
                "title": "Prepare renewal briefing",
                "objective": "Create a concise renewal briefing from project notes.",
                "workspace_path_hint": "Clients/Acme",
                "source_type": "workflow",
                "source_id": "spoofed/source",
                "success_criteria": ["Draft exists", "Open questions listed"],
                "plan": initial_plan,
            },
        )
        goal = self._tool_payload(create_payload)["result"]
        goal_id = goal["goal_id"]
        self.soft_assert(goal_id.startswith("goal_"), "create_goal should return a stable goal id")
        self.soft_assert_equal(goal["vault_name"], vault.name, "Goal should be scoped to the active vault")
        self.soft_assert_equal(goal["workspace_path_hint"], "Clients/Acme", "Workspace should be stored as a hint")
        self.soft_assert_equal(goal["plan"], initial_plan, "Goal plan should be stored as a JSON snapshot")
        self.soft_assert_equal(goal["source_type"], "chat", "Goal source type should be inferred from chat deps")
        self.soft_assert_equal(
            goal["source_id"],
            "goal_ops_chat_session",
            "Goal source id should use the active chat session id",
        )
        self.soft_assert_equal(
            goal["source_label"],
            "chat:goal_ops_chat_session",
            "Goal source label should be generated by the runtime",
        )

        updated_plan = [
            {"text": "Review source notes", "status": "completed"},
            {"text": "Draft briefing", "status": "in_progress"},
            {"text": "List open questions", "status": "pending"},
        ]
        update_payload = await tool.function(
            ctx,
            operation="update_goal",
            goal_id=goal_id,
            data={
                "plan": updated_plan,
                "metadata": {"draft_path": "Clients/Acme/renewal-briefing.md"},
                "reason": "Source review finished.",
            },
        )
        updated_goal = self._tool_payload(update_payload)["result"]
        self.soft_assert_equal(updated_goal["plan"], updated_plan, "update_goal should replace the plan snapshot")
        self.soft_assert_equal(
            updated_goal["metadata"],
            {"draft_path": "Clients/Acme/renewal-briefing.md"},
            "update_goal should preserve compact metadata",
        )

        checkpoint_payload = await tool.function(
            ctx,
            operation="checkpoint",
            goal_id=goal_id,
            data={
                "summary": "Reviewed sources and started the renewal briefing draft.",
                "current_state": "Risk section is started.",
                "next_actions": ["Pull source quotes", "Finish risk table"],
                "open_questions": ["Conservative or aggressive pricing recommendation?"],
                "risks": ["Security review owner remains unclear"],
            },
        )
        checkpoint = self._tool_payload(checkpoint_payload)["result"]
        self.soft_assert(checkpoint["checkpoint_id"].startswith("checkpoint_"), "Checkpoint id should be returned")
        self.soft_assert_equal(
            checkpoint["next_actions"],
            ["Pull source quotes", "Finish risk table"],
            "Checkpoint should preserve next actions structurally",
        )
        goal_ops_activity_events = self.events_since(goal_ops_activity_checkpoint)
        self.assert_event_contains(
            goal_ops_activity_events,
            name="goal_ops_goal_created",
            expected={
                "vault_name": vault.name,
                "operation": "create_goal",
                "goal_id": goal_id,
                "source_type": "chat",
                "source_id": "goal_ops_chat_session",
            },
        )
        self.assert_event_contains(
            goal_ops_activity_events,
            name="goal_ops_goal_updated",
            expected={
                "vault_name": vault.name,
                "operation": "update_goal",
                "goal_id": goal_id,
            },
        )
        self.assert_event_contains(
            goal_ops_activity_events,
            name="goal_ops_checkpoint_created",
            expected={
                "vault_name": vault.name,
                "operation": "checkpoint",
                "goal_id": goal_id,
                "checkpoint_id": checkpoint["checkpoint_id"],
            },
        )

        latest_payload = await tool.function(ctx, operation="get_goal", goal_id=goal_id)
        latest_goal = self._tool_payload(latest_payload)["result"]
        self.soft_assert_equal(
            latest_goal["latest_checkpoint"]["checkpoint_id"],
            checkpoint["checkpoint_id"],
            "get_goal should include the latest checkpoint",
        )
        self.soft_assert("steps" not in latest_goal, "Goal payload should not expose first-class step rows")

        list_payload = await tool.function(
            ctx,
            operation="list_goals",
            status="active",
            workspace_path_hint="Clients/Acme",
        )
        listed = self._tool_payload(list_payload)["result"]
        self.soft_assert_equal([item["goal_id"] for item in listed], [goal_id], "list_goals should filter by workspace hint")

        source_listed = GoalOpsStore().list_goals(
            vault_name=vault.name,
            source_type="chat",
            source_id="goal_ops_chat_session",
        )
        self.soft_assert_equal(
            [item["goal_id"] for item in source_listed],
            [goal_id],
            "Store-level goal queries should filter by source provenance",
        )
        current_session_payload = await tool.function(
            ctx,
            operation="list_goals",
            data={"source": "current_session", "status": "any"},
        )
        current_session_goals = self._tool_payload(current_session_payload)["result"]
        self.soft_assert_equal(
            [item["goal_id"] for item in current_session_goals],
            [goal_id],
            "list_goals should support semantic current-session source filtering",
        )

        runtime = get_runtime_context()
        workflow_source_id = f"{vault.name}/goal-source-workflow"
        async with runtime.task_coordinator.track_current_task(
            kind=ExecutionTaskKind.WORKFLOW,
            scope=workflow_vault_scope(vault.name),
            source=ExecutionTaskSource.TOOL,
            label=workflow_source_id,
            metadata={"vault": vault.name, "workflow_id": workflow_source_id},
        ) as task:
            workflow_ctx = SimpleNamespace(
                deps=SimpleNamespace(
                    vault_name=vault.name,
                    authoring_workflow_id=workflow_source_id,
                )
            )
            workflow_create_payload = await tool.function(
                workflow_ctx,
                operation="create_goal",
                data={
                    "title": "Workflow-created goal",
                    "objective": "Exercise workflow source provenance.",
                },
            )
            workflow_goal = self._tool_payload(workflow_create_payload)["result"]
            self.soft_assert_equal(workflow_goal["source_type"], "workflow", "Workflow ids should source goals")
            self.soft_assert_equal(workflow_goal["source_id"], workflow_source_id, "Workflow source id should be global id")
            self.soft_assert_equal(
                workflow_goal["source_task_id"],
                task.task_id,
                "Goal creation should capture the active execution task id when present",
            )

        context_source_id = f"{vault.name}/context/default.md/goal_ops_chat_session"
        context_ctx = SimpleNamespace(
            deps=SimpleNamespace(
                vault_name=vault.name,
                authoring_workflow_id=context_source_id,
            )
        )
        context_create_payload = await tool.function(
            context_ctx,
            operation="create_goal",
            data={
                "title": "Context-created goal",
                "objective": "Exercise context source provenance.",
            },
        )
        context_goal = self._tool_payload(context_create_payload)["result"]
        self.soft_assert_equal(context_goal["source_type"], "context", "Context script ids should source goals")
        self.soft_assert_equal(context_goal["source_id"], context_source_id, "Context source id should be global id")

        mutation_checkpoint = self.event_checkpoint()
        async with runtime.task_coordinator.track_current_task(
            kind=ExecutionTaskKind.WORKFLOW,
            scope=workflow_vault_scope(vault.name),
            source=ExecutionTaskSource.TOOL,
            label=f"{vault.name}/goal-scoped-write",
            metadata={
                "vault": vault.name,
                **goal_task_metadata(goal_id=goal_id),
            },
        ):
            mutate_vault_file(
                vault_path=vault,
                path="notes/goal-output.md",
                operation="write",
                mutator=lambda full_path: full_path.write_text("Goal output\n", encoding="utf-8"),
                create_parent=True,
            )
        mutation_events = self.events_since(mutation_checkpoint)
        self.assert_event_contains(
            mutation_events,
            name="execution_task_created",
            expected={"goal_id": goal_id},
        )
        self.assert_event_contains(
            mutation_events,
            name="task_file_mutation_recorded",
            expected={
                "goal_id": goal_id,
                "path": "notes/goal-output.md",
            },
        )

        activity_payload = await tool.function(ctx, operation="list_activity", goal_id=goal_id)
        activity = self._tool_payload(activity_payload)["result"]
        self.soft_assert_equal(len(activity), 1, "Goal activity should derive from task mutation rows")
        if activity:
            self.soft_assert_equal(activity[0]["goal_id"], goal_id, "Activity group should expose goal id")
            self.soft_assert_equal(
                activity[0]["mutations"][0]["path"],
                "notes/goal-output.md",
                "Goal activity should include the mutated path",
            )

        self.soft_assert(not self._table_exists("goal_artifacts"), "goal_ops should not create an artifact table")
        migration_status = get_system_migration_status(self._get_system_controller()._system_root)
        goal_target = next(target for target in migration_status.targets if target.db_name == "goal_ops")
        self.soft_assert_equal(goal_target.pending_versions, (), "goal_ops migration should be applied at startup")

        self._validate_goal_cleanup_endpoint(vault.name)

        self.teardown_scenario()
        self.assert_no_failures()

    def _tool_payload(self, raw) -> dict:
        if hasattr(raw, "return_value"):
            raw = raw.return_value
        payload = json.loads(raw)
        self.soft_assert_equal(payload.get("status"), "ok", "goal_ops tool call should succeed")
        return payload

    def _table_exists(self, table_name: str) -> bool:
        db_path = self._get_system_controller()._system_root / "goal_ops.db"
        conn = sqlite3.connect(db_path)
        try:
            row = conn.execute(
                """
                SELECT 1
                FROM sqlite_master
                WHERE type = 'table'
                  AND name = ?
                LIMIT 1
                """,
                (table_name,),
            ).fetchone()
        finally:
            conn.close()
        return row is not None

    def _validate_goal_cleanup_endpoint(self, vault_name: str) -> None:
        store = GoalOpsStore()
        old_completed = store.create_goal(
            vault_name=vault_name,
            title="Old completed cleanup target",
            objective="Should be removed by goal cleanup.",
        )
        store.update_goal(goal_id=old_completed["goal_id"], status="completed", reason="Finished.")
        store.checkpoint(goal_id=old_completed["goal_id"], summary="Cleanup cascade marker.")

        old_cancelled = store.create_goal(
            vault_name=vault_name,
            title="Old cancelled cleanup target",
            objective="Should be removed by goal cleanup.",
        )
        store.update_goal(goal_id=old_cancelled["goal_id"], status="cancelled", reason="No longer needed.")

        old_active = store.create_goal(
            vault_name=vault_name,
            title="Old active retained goal",
            objective="Should not be removed by cleanup.",
        )
        recent_completed = store.create_goal(
            vault_name=vault_name,
            title="Recent completed retained goal",
            objective="Should not be removed by age-filtered cleanup.",
        )
        store.update_goal(goal_id=recent_completed["goal_id"], status="completed", reason="Finished recently.")

        old_timestamp = (datetime.now(UTC).replace(microsecond=0) - timedelta(days=45)).isoformat()
        self._set_goal_updated_at(
            [old_completed["goal_id"], old_cancelled["goal_id"], old_active["goal_id"]],
            old_timestamp,
        )

        cleanup_response = self.call_api(
            "/api/system/goals/cleanup",
            method="POST",
            data={
                "vault_name": vault_name,
                "status": "completed_or_cancelled",
                "older_than_days": 30,
            },
        )
        self.soft_assert_equal(cleanup_response.status_code, 200, "Goal cleanup endpoint should succeed")
        cleanup_payload = cleanup_response.json()
        self.soft_assert_equal(cleanup_payload.get("deleted"), 2, "Cleanup should delete old completed/cancelled goals")

        remaining_ids = {
            goal["goal_id"]
            for goal in store.list_goals(vault_name=vault_name, status="active", limit=100)
        }
        self.soft_assert(old_active["goal_id"] in remaining_ids, "Cleanup should retain active goals")
        completed_ids = {
            goal["goal_id"]
            for goal in store.list_goals(vault_name=vault_name, status="completed", limit=100)
        }
        self.soft_assert(recent_completed["goal_id"] in completed_ids, "Cleanup should retain recent completed goals")
        self.soft_assert(not self._goal_exists(old_completed["goal_id"]), "Cleanup should delete old completed goals")
        self.soft_assert(not self._goal_exists(old_cancelled["goal_id"]), "Cleanup should delete old cancelled goals")
        self.soft_assert(
            not self._goal_has_activity_rows(old_completed["goal_id"]),
            "Goal cleanup should cascade checkpoints and events",
        )

    def _set_goal_updated_at(self, goal_ids: list[str], timestamp: str) -> None:
        db_path = self._get_system_controller()._system_root / "goal_ops.db"
        conn = sqlite3.connect(db_path)
        try:
            conn.executemany(
                "UPDATE goals SET updated_at = ? WHERE goal_id = ?",
                [(timestamp, goal_id) for goal_id in goal_ids],
            )
            conn.commit()
        finally:
            conn.close()

    def _goal_exists(self, goal_id: str) -> bool:
        db_path = self._get_system_controller()._system_root / "goal_ops.db"
        conn = sqlite3.connect(db_path)
        try:
            row = conn.execute("SELECT 1 FROM goals WHERE goal_id = ?", (goal_id,)).fetchone()
        finally:
            conn.close()
        return row is not None

    def _goal_has_activity_rows(self, goal_id: str) -> bool:
        db_path = self._get_system_controller()._system_root / "goal_ops.db"
        conn = sqlite3.connect(db_path)
        try:
            event_row = conn.execute("SELECT 1 FROM goal_events WHERE goal_id = ? LIMIT 1", (goal_id,)).fetchone()
            checkpoint_row = conn.execute(
                "SELECT 1 FROM goal_checkpoints WHERE goal_id = ? LIMIT 1",
                (goal_id,),
            ).fetchone()
        finally:
            conn.close()
        return event_row is not None or checkpoint_row is not None
