"""Integration scenario for goal_ops persistence and tool behavior."""

from __future__ import annotations

import json
import sqlite3
import sys
from pathlib import Path
from types import SimpleNamespace

sys.path.insert(0, str(Path(__file__).resolve().parents[4]))

from core.authoring.shared.tool_binding import resolve_tool_binding
from core.goals import GoalOpsStore
from core.runtime.execution_tasks import (
    ExecutionTaskKind,
    ExecutionTaskSource,
    goal_task_metadata,
    workflow_vault_scope,
)
from core.runtime.state import get_runtime_context
from core.system_migrations import get_system_migration_status
from core.vault_state.file_mutations import mutate_vault_file
from validation.core.base_scenario import BaseScenario


class GoalOpsScenario(BaseScenario):
    """Validate durable goal_ops operations and batch step semantics."""

    async def test_scenario(self):
        vault = self.create_vault("GoalOpsVault")
        await self.start_system()

        binding = resolve_tool_binding(["goal_ops"], vault_path=str(vault))
        self.soft_assert_equal(binding.tool_names(), ["goal_ops"], "goal_ops should bind through the tool registry")
        tool = binding.tool_specs[0].tool_function
        ctx = SimpleNamespace(deps=SimpleNamespace(vault_name=vault.name, session_id="goal_ops_chat_session"))

        create_payload = await tool.function(
            ctx,
            operation="create_goal",
            data={
                "title": "Prepare renewal briefing",
                "objective": "Create a concise renewal briefing from project notes.",
                "workspace_path_hint": "Clients/Acme",
                "source_type": "workflow",
                "source_id": "spoofed/source",
                "success_criteria": ["Draft exists", "Open questions listed"],
                "steps": [
                    {"title": "Review notes"},
                    {"title": "Extract risks"},
                    {"title": "Draft briefing"},
                ],
            },
        )
        created = self._tool_payload(create_payload)
        goal = created["result"]
        goal_id = goal["goal_id"]
        self.soft_assert(goal_id.startswith("goal_"), "create_goal should return a stable goal id")
        self.soft_assert_equal(goal["vault_name"], vault.name, "Goal should be scoped to the active vault")
        self.soft_assert_equal(
            goal["workspace_path_hint"],
            "Clients/Acme",
            "Workspace should be stored as a non-authoritative hint",
        )
        self.soft_assert_equal(goal["source_type"], "chat", "Goal source type should be inferred from chat deps")
        self.soft_assert_equal(
            goal["source_id"],
            "goal_ops_chat_session",
            "Goal source id should use the active chat session id",
        )
        self.soft_assert_equal(
            goal["source_label"],
            "chat:goal_ops_chat_session",
            "Goal source label should be generated by the runtime",
        )
        self.soft_assert_equal(
            [step["position"] for step in goal["steps"]],
            [10, 20, 30],
            "Initial steps should get sparse positions from array order",
        )

        replace_payload = await tool.function(
            ctx,
            operation="replace_steps",
            goal_id=goal_id,
            data={
                "reason": "User simplified the plan.",
                "steps": [
                    {"title": "Draft briefing", "position": 30},
                    {"title": "Review source notes", "position": 10},
                    {"title": "List open questions", "position": 20},
                ],
            },
        )
        replaced = self._tool_payload(replace_payload)["result"]
        active_steps = replaced["steps"]
        self.soft_assert_equal(
            [step["title"] for step in active_steps],
            ["Review source notes", "List open questions", "Draft briefing"],
            "replace_steps should return steps ordered by explicit position",
        )
        self.soft_assert_equal(
            len(self._superseded_step_rows(goal_id)),
            3,
            "replace_steps should mark removed active steps superseded rather than deleting them",
        )

        first_step_id = active_steps[0]["step_id"]
        second_step_id = active_steps[1]["step_id"]
        update_payload = await tool.function(
            ctx,
            operation="update_steps",
            goal_id=goal_id,
            data={
                "reason": "Source review finished.",
                "updates": [
                    {"step_id": first_step_id, "status": "completed"},
                    {"step_id": second_step_id, "status": "in_progress", "position": 15},
                ],
            },
        )
        updated_steps = self._tool_payload(update_payload)["result"]["steps"]
        self.soft_assert_equal(
            [(step["title"], step["status"], step["position"]) for step in updated_steps],
            [
                ("Review source notes", "completed", 10),
                ("List open questions", "in_progress", 15),
                ("Draft briefing", "pending", 30),
            ],
            "update_steps should batch status and order changes while keeping completed steps in the ordered plan",
        )
        completed = GoalOpsStore().list_steps(goal_id=goal_id, include_superseded=True)
        completed_step = next(step for step in completed if step["step_id"] == first_step_id)
        self.soft_assert_equal(completed_step["status"], "completed", "Completed step should be persisted")

        checkpoint_payload = await tool.function(
            ctx,
            operation="checkpoint",
            goal_id=goal_id,
            data={
                "step_id": second_step_id,
                "summary": "Reviewed sources and started open-question list.",
                "current_state": "Draft is not started yet.",
                "next_actions": ["Draft briefing", "Ask user about pricing stance"],
                "open_questions": ["Conservative or aggressive pricing recommendation?"],
                "risks": ["Security review owner remains unclear"],
            },
        )
        checkpoint = self._tool_payload(checkpoint_payload)["result"]
        self.soft_assert(checkpoint["checkpoint_id"].startswith("checkpoint_"), "Checkpoint id should be returned")
        self.soft_assert_equal(
            checkpoint["next_actions"],
            ["Draft briefing", "Ask user about pricing stance"],
            "Checkpoint should preserve next actions structurally",
        )

        latest_payload = await tool.function(ctx, operation="get_goal", goal_id=goal_id)
        latest_goal = self._tool_payload(latest_payload)["result"]
        self.soft_assert_equal(
            latest_goal["latest_checkpoint"]["checkpoint_id"],
            checkpoint["checkpoint_id"],
            "get_goal should include the latest checkpoint",
        )

        events_payload = await tool.function(ctx, operation="list_events", goal_id=goal_id)
        events = self._tool_payload(events_payload)["result"]
        event_types = [event["event_type"] for event in events]
        self.soft_assert(
            {"created", "plan_changed", "status_changed", "checkpoint"}.issubset(set(event_types)),
            "Goal events should capture creation, plan changes, status updates, and checkpoints",
        )

        list_payload = await tool.function(
            ctx,
            operation="list_goals",
            status="active",
            workspace_path_hint="Clients/Acme",
            source_type="chat",
            source_id="goal_ops_chat_session",
        )
        listed = self._tool_payload(list_payload)["result"]
        self.soft_assert_equal(
            [item["goal_id"] for item in listed],
            [goal_id],
            "list_goals should filter by workspace hint and source provenance",
        )

        runtime = get_runtime_context()
        workflow_source_id = f"{vault.name}/goal-source-workflow"
        async with runtime.task_coordinator.track_current_task(
            kind=ExecutionTaskKind.WORKFLOW,
            scope=workflow_vault_scope(vault.name),
            source=ExecutionTaskSource.TOOL,
            label=workflow_source_id,
            metadata={"vault": vault.name, "workflow_id": workflow_source_id},
        ) as task:
            workflow_ctx = SimpleNamespace(
                deps=SimpleNamespace(
                    vault_name=vault.name,
                    authoring_workflow_id=workflow_source_id,
                )
            )
            workflow_create_payload = await tool.function(
                workflow_ctx,
                operation="create_goal",
                data={
                    "title": "Workflow-created goal",
                    "objective": "Exercise workflow source provenance.",
                },
            )
            workflow_goal = self._tool_payload(workflow_create_payload)["result"]
            self.soft_assert_equal(
                workflow_goal["source_type"],
                "workflow",
                "Authoring workflow ids should create workflow-sourced goals",
            )
            self.soft_assert_equal(
                workflow_goal["source_id"],
                workflow_source_id,
                "Workflow source id should be the workflow global id",
            )
            self.soft_assert_equal(
                workflow_goal["source_task_id"],
                task.task_id,
                "Goal creation should capture the active execution task id when present",
            )

        context_source_id = f"{vault.name}/context/default.md/goal_ops_chat_session"
        context_ctx = SimpleNamespace(
            deps=SimpleNamespace(
                vault_name=vault.name,
                authoring_workflow_id=context_source_id,
            )
        )
        context_create_payload = await tool.function(
            context_ctx,
            operation="create_goal",
            data={
                "title": "Context-created goal",
                "objective": "Exercise context source provenance.",
            },
        )
        context_goal = self._tool_payload(context_create_payload)["result"]
        self.soft_assert_equal(
            context_goal["source_type"],
            "context",
            "Context script ids should create context-sourced goals",
        )
        self.soft_assert_equal(
            context_goal["source_id"],
            context_source_id,
            "Context source id should be the context global id",
        )

        mutation_checkpoint = self.event_checkpoint()
        async with runtime.task_coordinator.track_current_task(
            kind=ExecutionTaskKind.WORKFLOW,
            scope=workflow_vault_scope(vault.name),
            source=ExecutionTaskSource.TOOL,
            label=f"{vault.name}/goal-scoped-write",
            metadata={
                "vault": vault.name,
                **goal_task_metadata(goal_id=goal_id, step_id=second_step_id),
            },
        ):
            mutate_vault_file(
                vault_path=vault,
                path="notes/goal-output.md",
                operation="write",
                mutator=lambda full_path: full_path.write_text("Goal output\n", encoding="utf-8"),
                create_parent=True,
            )
        mutation_events = self.events_since(mutation_checkpoint)
        self.assert_event_contains(
            mutation_events,
            name="execution_task_created",
            expected={"goal_id": goal_id, "step_id": second_step_id},
        )
        self.assert_event_contains(
            mutation_events,
            name="task_file_mutation_recorded",
            expected={
                "goal_id": goal_id,
                "step_id": second_step_id,
                "path": "notes/goal-output.md",
            },
        )

        activity_payload = await tool.function(ctx, operation="list_activity", goal_id=goal_id)
        activity = self._tool_payload(activity_payload)["result"]
        self.soft_assert_equal(len(activity), 1, "Goal activity should derive from task mutation rows")
        if activity:
            self.soft_assert_equal(activity[0]["goal_id"], goal_id, "Activity group should expose goal id")
            self.soft_assert_equal(activity[0]["step_id"], second_step_id, "Activity group should expose step id")
            self.soft_assert_equal(
                activity[0]["mutations"][0]["path"],
                "notes/goal-output.md",
                "Goal activity should include the mutated path",
            )

        files_payload = await tool.function(ctx, operation="list_related_files", goal_id=goal_id)
        related_files = self._tool_payload(files_payload)["result"]
        self.soft_assert_equal(
            [item["path"] for item in related_files],
            ["notes/goal-output.md"],
            "Related files should be derived from existing mutation provenance",
        )

        self.soft_assert(not self._table_exists("goal_artifacts"), "goal_ops should not create an artifact table")
        migration_status = get_system_migration_status(self._get_system_controller()._system_root)
        goal_target = next(target for target in migration_status.targets if target.db_name == "goal_ops")
        self.soft_assert_equal(goal_target.pending_versions, (), "goal_ops migration should be applied at startup")

        self.teardown_scenario()
        self.assert_no_failures()

    def _tool_payload(self, raw) -> dict:
        if hasattr(raw, "return_value"):
            raw = raw.return_value
        payload = json.loads(raw)
        self.soft_assert_equal(payload.get("status"), "ok", "goal_ops tool call should succeed")
        return payload

    def _superseded_step_rows(self, goal_id: str) -> list[sqlite3.Row]:
        db_path = self._get_system_controller()._system_root / "goal_ops.db"
        conn = sqlite3.connect(db_path)
        conn.row_factory = sqlite3.Row
        try:
            return conn.execute(
                """
                SELECT *
                FROM goal_steps
                WHERE goal_id = ?
                  AND status = 'superseded'
                """,
                (goal_id,),
            ).fetchall()
        finally:
            conn.close()

    def _table_exists(self, table_name: str) -> bool:
        db_path = self._get_system_controller()._system_root / "goal_ops.db"
        conn = sqlite3.connect(db_path)
        try:
            row = conn.execute(
                """
                SELECT 1
                FROM sqlite_master
                WHERE type = 'table'
                  AND name = ?
                LIMIT 1
                """,
                (table_name,),
            ).fetchone()
        finally:
            conn.close()
        return row is not None
